conditions:
  misionActiva27: "tag marcaMisionActiva27"
  misionCompletada27: "tag marcaMisionCompletada27"

####################################################################################################

events:
  iniciarMision27: "folder agregarMarcaMisionActiva27,iniciarObjetivoMision27"
  agregarMarcaMisionActiva27: "tag add marcaMisionActiva27"
  iniciarObjetivoMision27: "objective start objFabricarMesaTrabajo"
  
  mensajeAyudaMision27: "notify \n&6&lMisión 27:\n&r Para fabricar una &bMesa de herreria &rnecesitarás 4 bloques de cualquier madera y 2 lingotes de hierro, los cuales puedes obtener del tronco de cualquier árbol y cocinando menas de hierro respectivamente.\n&r"
  
  completarMision27: "folder eliminarMarcaMisionActiva27,agregarMarcaMisionCompletada27,notificacionMisionCompletada27,recompensaMision27,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva27: "tag delete marcaMisionActiva27"
  agregarMarcaMisionCompletada27: "tag add marcaMisionCompletada27"
  notificacionMisionCompletada27: "notify &7----------------------------------------\n&6&l¡Misión 27 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7----------------------------------------"
  recompensaMision27: "command eco give %player% 500"
  recompensaExpClase: "mmoclassexperience 100"
  notificacionRecompensaExpClase: "notify &aHas conseguido 100 exp de clase."

####################################################################################################

objectives:
  objFabricarMesaHerreria: "craft mesaHerreria 1 events:completarMision27"
  
####################################################################################################

items:
  mesaHerreria: "SMITHING_TABLE"