conditions:
  misionActiva5: "tag marcaMisionActiva5"
  misionCompletada5: "tag marcaMisionCompletada5"

####################################################################################################

events:
  iniciarMision5: "folder agregarMarcaMisionActiva5,iniciarObjetivoMision5"
  agregarMarcaMisionActiva5: "tag add marcaMisionActiva5"
  iniciarObjetivoMision5: "objective start objFabricarMesaTrabajo"
  
  mensajeAyudaMision5: "notify \n&6&lMisión 5:\n&r Para fabricar una &bMesa de trabajo &rnecesitarás 4 bloques de cualquier madera, los cuales puedes obtener del tronco de cualquier árbol.\n&r"
  
  completarMision5: "folder eliminarMarcaMisionActiva5,agregarMarcaMisionCompletada5,notificacionMisionCompletada5,recompensaMision5,recompensaComida,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva5: "tag delete marcaMisionActiva5"
  agregarMarcaMisionCompletada5: "tag add marcaMisionCompletada5"
  notificacionMisionCompletada5: "run ^notify &7----------------------------------------\n&6&l¡Misión 5 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7---------------------------------------- ^notify io:sound soundcategory:players sound:ui.toast.challenge_complete"
  recompensaMision5: "command eco give %player% 250"
  recompensaComida: "run ^command give %player% bread 3 ^notify &aHas conseguido 3 Panes."
  recompensaExpClase: "mmoclassexperience 50"
  notificacionRecompensaExpClase: "notify &aHas conseguido 50 exp de clase."

####################################################################################################

objectives:
  objFabricarMesaTrabajo: "craft mesaTrabajo 1 events:completarMision5"
  
####################################################################################################

items:
  mesaTrabajo: "CRAFTING_TABLE"