menus:
  checkpointMuerte:
    title: "&b&lPunto de control de muerte"
    command: "/puntomuerte"
    height: 3
    slots:
      13: "botonCheckpointMuerte1,botonCheckpointMuerte2"
    items:
      botonCheckpointMuerte1:
        item: "iconoCheckpointMuerte"
        condition: "!Checkpoint_Muerte-Controlador_Checkpoints.checkpointMuerteActivo"
        text:
        - "&b¿Qué es el punto de control de muerte?"
        - ""
        - "&7Es un punto de control que aparecerá en tu brújula"
        - "&7justo después de morir, para ayudarte a llegar a tu"
        - "&7lugar de anterior."
        - ""
        - "&7El punto de control no aparecerá"
        - "&7si mueres en una Mazmorra."
        - ""
        - "&7Actualmente lo tienes &cdesactivado&7."
        - ""
        - "&7[&aClic&7] para activar el punto de control."
        click: "Checkpoint_Muerte-Controlador_Checkpoints.activacionCheckpointMuerte"
      botonCheckpointMuerte2:
        item: "iconoCheckpointMuerte"
        condition: "Checkpoint_Muerte-Controlador_Checkpoints.checkpointMuerteActivo"
        text:
        - "&b¿Qué es el punto de control de muerte?"
        - ""
        - "&7Es un punto de control que aparecerá en tu brújula"
        - "&7justo después de morir, para ayudarte a llegar a tu"
        - "&7lugar de muerte anterior."
        - ""
        - "&7El punto de control no aparecerá"
        - "&7si mueres en una Mazmorra."
        - ""
        - "&7Actualmente lo tienes &aactivado&7."
        - ""
        - "&7[&aClic&7] para desactivar el punto de control."
        click: "Checkpoint_Muerte-Controlador_Checkpoints.desactivacionCheckpointMuerte"

items:
  iconoCheckpointMuerte: "SOUL_CAMPFIRE"