conditions:
  misionActiva80: "tag marcaMisionActiva80"
  misionCompletada80: "tag marcaMisionCompletada80"
  misionInfoRecibidaPaladin: "tag marcaInfoRecibidaPaladin"
  misionEnCursoPaladin: "tag marcaMisionEnCursoPaladin"

####################################################################################################

events:
  iniciarMision80: "tag add marcaMisionActiva80"
  
  mensajeAyudaMision80: "folder mensajeAyudaMision80_1,mensajeAyudaMision80_2,mensajeAyudaMision80_3"
  mensajeAyudaMision80_1: "notify \n&6&lMisión 80:\n&r El &6Rey de Valor &rse encuentra en el Salón del Trono del Palacio de Valor, el cual está ubicado en el &b/spawn&r.\n&r conditions:!misionInfoRecibidaPaladin,misionEnCursoPaladin"
  mensajeAyudaMision80_2: "folder agregarObjetivosBrujula conditions:misionInfoRecibidaPaladin,!misionEnCursoPaladin"
  mensajeAyudaMision80_3: "folder agregarObjetivosBrujula conditions:misionInfoRecibidaPaladin,misionEnCursoPaladin"

  agregarObjetivosBrujula: "folder limpiarBrujula,mostrarBrujula,mostrarObjBrujulaPaladin,mostrarObjBrujulaCrafburgo,notificacionObjBrujula"
  limpiarBrujula: "clearcompass"
  mostrarBrujula: "command calebcompass show %player%"
  mostrarObjBrujulaPaladin: "compasstrack 853.5;13;991.5;Zona1 conditions:misionInfoRecibidaPaladin,!misionEnCursoPaladin"
  mostrarObjBrujulaCrafburgo: "compasstrack 470.5;34;711.5;Zona1 conditions:misionInfoRecibidaPaladin,misionEnCursoPaladin"
  notificacionObjBrujula: "notify \n&6&lMisión 80:\n&r Para llegar a tu objetivo ve al &b/spawn &ry sigue la dirección que te indica la brújula (&f ▽ &r).\n&r"

  notificacionNuevoMensajeAyuda: "notify &7----------------------------------------\n&6&lMisiones:\n&e¡Tienes un nuevo mensaje de ayuda disponible en el menú de &r/misiones!\n&7----------------------------------------"
  agregarMarcaInfoRecibidaPaladin: "tag add marcaInfoRecibidaPaladin"

  completarParte1: "folder agregarMarcaInfoRecibidaPaladin,notificacionNuevoMensajeAyuda delay:2 conditions:!misionInfoRecibidaPaladin,!misionEnCursoPaladin"

  agregarMarcaMisionEnCursoPaladin: "tag add marcaMisionEnCursoPaladin"
  darPermisoCrafburgo: "command lp user %player% permission set group.region2"
  iniciarObjLlegarCrafburgo: "objective start objLlegarCrafburgo"
  completarParte2: "folder agregarMarcaMisionEnCursoPaladin,darPermisoCrafburgo,iniciarObjLlegarCrafburgo,notificacionNuevoMensajeAyuda delay:2 conditions:misionInfoRecibidaPaladin,!misionEnCursoPaladin"

  completarMision80: "folder limpiarBrujula,eliminarMarcaMisionActiva80,eliminarMarcaInfoRecibidaPaladin,eliminarMarcaMisionEnCursoPaladin,agregarMarcaMisionCompletada80,notificacionMisionCompletada80,recompensaMision80,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva80: "tag delete marcaMisionActiva80"
  eliminarMarcaInfoRecibidaPaladin: "tag delete marcaInfoRecibidaPaladin"
  eliminarMarcaMisionEnCursoPaladin: "tag delete marcaMisionEnCursoPaladin"
  agregarMarcaMisionCompletada80: "tag add marcaMisionCompletada80"
  notificacionMisionCompletada80: "run ^notify &7----------------------------------------\n&6&l¡Misión 80 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7---------------------------------------- ^notify io:sound soundcategory:players sound:ui.toast.challenge_complete"
  recompensaMision80: "command eco give %player% 10000"
  recompensaExpClase: "mmoclassexperience 1250"
  notificacionRecompensaExpClase: "notify &aHas conseguido 1250 exp de clase."

####################################################################################################

objectives:
  objLlegarCrafburgo: "location 470.5;34;711.5;Zona1 15 events:completarMision80 conditions:misionInfoRecibidaPaladin,misionEnCursoPaladin"