package:
  templates:
    - Sistema_Puertas-Puertas

conditions:
  requerimientoEntradaPuerta: "and estarEnRangoPuerta,!claseRequerida"
  estarEnRangoPuerta: "location $ubicacionSalida$"
  claseRequerida: "variable %ph.mmocore_class% Humano"

events:
  eventoPuerta: "folder eventoEntrada,notificacionEntrada,notificacionSonidoEntrada,notificacionEntradaBloqueada,notificacionSonidoEntradaBloqueada,eventoSalida,notificacionSalida,notificacionSonidoSalida"
  notificacionEntradaBloqueada: "notify &cNecesitas haber elegido una clase para pasar a la siguiente zona."
  notificacionSonidoEntradaBloqueada: "notify io:sound soundcategory:blocks sound:$efectoSonidoEntradaBloqueada$ condition:requerimientoEntradaPuerta"

variables:
  ubicacionEntrada: 1820.5;61;-446.5;Zona1
  pitchYawEntrada: -180;0
  ubicacionSalida: 1819.5;63;-436.5;Zona1
  mensajeEntrada: "&aHas pasado a la siguiente etapa del tutorial"
  efectoSonidoEntradaBloqueada: "entity.villager.no"
  mensajeSalida: ""