package:
  templates:
    - Sistema_Puertas-Puertas

conditions:
  clasePorDefecto: "variable %ph.mmocore_class% Humano"

events:
  eventoPuerta: "if requerimientoEntradaPuerta eventoEntradaPuerta else eventoErrorPuerta"
  eventoEntradaPuerta: "if !clasePorDefecto eventoEntradaPuerta2 else notificacionEntradaBloqueada"
  eventoEntradaPuerta2: "folder eventoEntrada,notificacionEntrada,notificacionSonidoEntrada,agregarMarcaPasandoPuerta,iniciarObjEliminarMarcaPasandoPuerta"
  notificacionEntradaBloqueada: "folder notificacionEntradaBloqueada1,notificacionEntradaBloqueada2"
  notificacionEntradaBloqueada1: "notify &cNecesitas haber elegido una clase para pasar a la siguiente zona."
  notificacionEntradaBloqueada2: "notify io:sound soundcategory:blocks sound:$efectoSonidoEntradaBloqueada$"

variables:
  ubicacionEntrada: 1820.5;61;-446.5;Zona1
  pitchYawEntrada: -180;0
  ubicacionSalida: 1819.5;63;-436.5;Zona1
  mensajeEntrada: Has pasado a la siguiente etapa del tutorial
  efectoSonidoEntradaBloqueada: entity.villager.no