package:
  templates:
    - Sistema_Puertas-Puertas

variables:
  ubicacionEntrada: 1040;61;343;Zona1
  pitchYawEntrada: 180;10
  ubicacionSalida: 1444;76;-594;Zona1
  pitchYawSalida: 0;0
  mensajeEntrada: "&6Has entrado en el Palacio Real"
  mensajeSalida: "&6Has salido del Palacio Real"