conditions:
  misionActiva46: "tag marcaMisionActiva46"
  misionCompletada46: "tag marcaMisionCompletada46"

####################################################################################################

events:
  iniciarMision46: "folder agregarMarcaMisionActiva46,iniciarObjetivoMision46"
  agregarMarcaMisionActiva46: "tag add marcaMisionActiva46"
  iniciarObjetivoMision46: "objective start objColocarGema"
  
  mensajeAyudaMision46: "notify \n&6&lMisión 46:\n&rPuedes mejorar tus armas y armaduras colocandoles &bGemas. &rLas gemas son objetos que te aportan mejoras de estadísticas, se pueden comprar en la tienda de gemas o conseguirlas en las mazmorras. Para completar la misión coloca una &bGema de Mana de nivel II &ra tu &bEspada de Amatista&r.\n \n&7Nota: Puedes fabricar la espada con 4 esencias de amatista y una Espada de netherita.\n&r"
  
  completarMision46: "folder eliminarMarcaMisionActiva46,agregarMarcaMisionCompletada46,notificacionMisionCompletada46,recompensaMision46,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva46: "tag delete marcaMisionActiva46"
  agregarMarcaMisionCompletada46: "tag add marcaMisionCompletada46"
  notificacionMisionCompletada46: "run ^notify &7----------------------------------------\n&6&l¡Misión 46 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7---------------------------------------- ^notify io:sound soundcategory:players sound:ui.toast.challenge_complete"
  recompensaMision46: "command eco give %player% 500"
  recompensaExpClase: "mmoclassexperience 200"
  notificacionRecompensaExpClase: "notify &aHas conseguido 200 exp de clase."

####################################################################################################

objectives:
  objColocarGema: "mmoitemapplygem ESPADA_GEMA ESPADA_AMATISTA_1 GEMA_MANA_2 events:completarMision46"