package:
  templates:
    - Sistema_Puertas-Puertas

variables:
  ubicacionEntrada: 1587;92;-429;Zona1
  pitchYawEntrada: 90;0
  ubicacionSalida: 959;61;434;Zona1
  pitchYawSalida: -90;0
  mensajeEntrada: "&6Has entrado en la Tienda de Mascotas"
  mensajeSalida: "&6Has salido de la Tienda de Mascotas"