conditions:
  misionActiva15: "tag marcaMisionActiva15"
  misionCompletada15: "tag marcaMisionCompletada15"
  misionDiariaPaseBatallaCompletada: "variable %math.calc:ph.battlepass_completed_quests_daily*1% [1-5]"

####################################################################################################

events:
  iniciarMision15: "folder agregarMarcaMisionActiva15,iniciarObjetivoMision15"
  agregarMarcaMisionActiva15: "tag add marcaMisionActiva15"
  iniciarObjetivoMision15: "objective start objCompletarMisionDiariaPaseBatalla"
  
  mensajeAyudaMision15: "notify \n&6&lMisión 15:\n&r El comando &b/pase&r te permite visualizar el menú del &bPase de Batalla&r. Conforme vayas completando misiones del Pase de Batalla irás obteniendo puntos, y por cada 150 puntos que obtengas podrás reclamar recompensas.\n&r"
  
  completarMision15: "folder eliminarMarcaMisionActiva15,agregarMarcaMisionCompletada15,notificacionMisionCompletada15,recompensaMision15,recompensaReparador,recompensaReparadorMensaje,recompensaExpClase,notificacionRecompensaExpClase"
  eliminarMarcaMisionActiva15: "tag delete marcaMisionActiva15"
  agregarMarcaMisionCompletada15: "tag add marcaMisionCompletada15"
  notificacionMisionCompletada15: "notify &7----------------------------------------\n&6&l¡Misión 15 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7----------------------------------------"
  recompensaMision15: "command eco give %player% 250"
  recompensaReparador: "mmoitemgive CONSUMABLE REPARADOR_250 2"
  recompensaReparadorMensaje: "notify &aHas conseguido 2 Reparadores Básicos."
  recompensaExpClase: "mmoclassexperience 100"
  notificacionRecompensaExpClase: "notify &aHas conseguido 100 exp de clase."

####################################################################################################

objectives:
  objCompletarMisionDiariaPaseBatalla: "delay 5 ticks interval:5 conditions:misionDiariaPaseBatallaCompletada events:completarMision15"