package:
  templates:
    - Sistema_Puertas-Puertas

conditions:
  permisoRequerido: "permission tutorial.puerta"

events:
  eventoPuerta: "if requerimientoEntradaPuerta eventoEntradaPuerta else eventoErrorPuerta"
  eventoEntradaPuerta: "if permisoRequerido eventoEntradaPuerta2 else notificacionEntradaBloqueada"
  eventoEntradaPuerta2: "folder eventoEntrada,notificacionEntrada,notificacionSonidoEntrada,agregarMarcaPasandoPuerta,iniciarObjEliminarMarcaPasandoPuerta"
  notificacionEntradaBloqueada: "run ^notify io:sound soundcategory:blocks sound:$efectoSonidoEntradaBloqueada$ ^notify &cNecesitas haber derrotado al Goblin para usar la puerta."

variables:
  ubicacionEntrada: 1805.5;59;-678.5;Zona1
  pitchYawEntrada: -180;0
  ubicacionSalida: 1804.5;61;-668.5;Zona1
  mensajeEntrada: Has pasado a la siguiente etapa del tutorial
  efectoSonidoEntradaBloqueada: entity.villager.no