conversations:
  ReyValor12:
    quester: "&6&lRey de Valor"
    first: "saludo,saludo2,saludo3"
    NPC_options:
      saludo:
        text: "¡Ah %player%! Te has destacado en cada una de las misiones que te he encomendado. Tu valor y dedicación han honrado a nuestro reino."
        pointer: "a1"
        conditions: "!Misiones_Principiante-Mision_80.misionInfoRecibidaPaladin,!Misiones_Principiante-Mision_80.mazmorraCompletadaPaladin"
      b1:
        text: "Tus hazañas no han pasado desapercibidas, querido defensor. El reino entero habla de tus logros y te agradece profundamente por tu valentía. Has demostrado ser un verdadero héroe."
        pointer: "a2"
      b2:
        text: "Y ahora, querido aventurero, tengo una nueva misión para ti. Necesito que te dirijas al puente que cruza el rio grande y te encuentres con nuestro fiel paladín. Él te dará acceso a la siguiente ciudad."
        pointer: "a3"  
      b2_2:
        text: "Necesito que te dirijas al puente que cruza el rio grande y te encuentres con nuestro fiel paladín. Él te dará acceso a la siguiente ciudad."
        pointer: "a3"        
      b3:
        text: "Confío en ti, valiente guerrero. Sé que cumplirás esta misión con la misma dedicación y determinación que has demostrado hasta ahora. Nuestro reino cuenta contigo."
        pointer: "a4"
        events: "Misiones_Principiante-Mision_80.completarParte1"
#####################################################################
      saludo2:
        text: "Ah, valiente aventurero, veo que has regresado. ¿Cómo va tu progreso en la misión que te encomendé? ¿Has hablado con el paladin?"
        pointer: "c1,c2"
        conditions: "Misiones_Principiante-Mision_80.misionInfoRecibidaPaladin,!Misiones_Principiante-Mision_80.mazmorraCompletadaPaladin"
      d1:
        text: "Entiendo, valiente guerrero. No demores tu partida, grandes aventuras te depara Crafburgo."
      d2:
        text: "Por supuesto, presta atención."
        pointer: "c3,c4"
#####################################################################
    player_options:
      a1:
        text: "Mi Rey, ha sido un honor servir a su lado y proteger nuestro reino."
        pointer: "b1"
      a2:
        text: "Es un privilegio luchar por la seguridad y prosperidad de nuestro reino."
        pointer: "b2"
      a3:
        text: "Entendido, mi Rey. Me pondré en marcha de inmediato"
        pointer: "b3"
        conditions: "!Misiones_Principiante-Mision_80.misionInfoRecibidaPaladin"
      
#####################################################################
      c1:
        text: "Mi Rey, aún no he podido ir."
        pointer: "d1"
      c2:
        text: "¿Su majestad, podría indicarme donde está el paladin?"
        pointer: "d2"
      c3:
        text: "Soy todo oidos, Su majestad."
        pointer: "b2_2"
      c4:
        text: "Mejor otro día, Su majestad."
        pointer: "d1"
#####################################################################