conditions:
  misionActivaPrueba02: "tag marcaMisionActivaPrueba02"
  misionCompletadaPrueba02: "tag marcaMisionCompletadaPrueba02"
  llegarNivel3Clase: "mmoclass * 3"

####################################################################################################

events:
  mensajeAyudaMisionPrueba02: "notify \n&6&lMisión de Prueba 2:\n&r Conforme vayas derrotando enemigos o subiendo de nivel tus profesiones irás obteniendo experiencia para subir de nivel. Los jefes de mazmorras otorgan una mayor cantidad de experiencia al ser derrotados.\n&r"
  
  iniciarMisionPrueba02: "folder agregarMarcaMisionActivaPrueba02,iniciarObjetivoMisionPrueba02"
  agregarMarcaMisionActivaPrueba02: "tag add marcaMisionActivaPrueba02"
  iniciarObjetivoMisionPrueba02: "objective start objPicarMenasDiamante"
  
  completarMisionPrueba02: "folder recompensaMisionPrueba02,agregarMarcaMisionCompletadaPrueba02,notificacionMisionCompletadaPrueba02,recompensaExpClase,notificacionRecompensaExpClase"
  recompensaMisionPrueba02: "command eco give %player% 200"
  recompensaExpClase: "mmoclassexperience 200"
  notificacionRecompensaExpClase: "notify &aHas conseguido 200 exp de clase."
  agregarMarcaMisionCompletadaPrueba02: "tag add marcaMisionCompletadaPrueba02"
  notificacionMisionCompletadaPrueba02: "notify &7----------------------------------------\n&6&l¡Misión de Prueba 2 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7----------------------------------------"

####################################################################################################

objectives:
  objPicarMenasDiamante: "block .*DIAMOND_ORE -10 events:completarMisionPrueba02"
  