menus:
  menuMisiones:
    height: 6
    title: "§f§f⠜"
    # open_conditions: "misionTutorialCompletada"
    # open_events: "sonidoAbrirMenu"
    # close_events: "sonidoCerrarMenu"
    # bind: "objetoMision"
    command: "/misionestest"
    slots:
      10: "botonMisionDisponible21,botonMisionActiva21,botonMisionCompletada21,botonMisionBloqueada21"
      11: "botonMisionDisponible22,botonMisionActiva22,botonMisionCompletada22,botonMisionBloqueada22"
    items:
#####################################################################
      botonMisionDisponible22:
        item: "botonMisionActiva"
        amount: 1
        conditions: "Misiones_Principiante-Mision_21.misionCompletada21,!Misiones_Principiante-Mision_22.misionActiva22"
        close: true
        text:
        - "&6&l[Misión 22]: &eEn busca de diamantes"
        - "&r "
        - "&aObjetivo:"
        - "&7&oPica &f&o10 menas de Diamante&7&o."
        - "&r "
        - "&7[&aClic izquierdo&7] para iniciar la misión."
        click:
          left: "Misiones_Principiante-Mision_22.mensajeAyudaMision22,Misiones_Principiante-Mision_22.iniciarMision22" 
      botonMisionActiva22:
        item: "botonMisionActiva"
        amount: 1
        conditions: "Misiones_Principiante-Mision_22.misionActiva22,!Misiones_Principiante-Mision_22.misionCompletada22"
        close: true
        text:
        - "&6&l[Misión 22]: &eEn busca de diamantes"
        - "&r "
        - "&aObjetivo:"
        - "&7&oPica &f&o10 menas de Diamante&7&o."
        - "&r "
        - "&7[&aClic izquierdo&7] para recibir un mensaje de ayuda acerca de la misión."
        click:
          left: "Misiones_Principiante-Mision_22.mensajeAyudaMision22" 
      botonMisionCompletada22:
        item: "botonMisionCompletada"
        amount: 1
        conditions: "Misiones_Principiante-Mision_22.misionCompletada22"
        text:
        - "&3¡Misión completada!"
        - "&6&l[Misión 22]: &eEn busca de diamantes"
        - "&r "
        - "&7&oPica &f&o10 menas de Diamante&7&o."
      botonMisionBloqueada22:
        item: "botonMisionBloqueada"
        amount: 1
        conditions: "!Misiones_Principiante-Mision_21.misionCompletada21"

#####################################################################
items:
  botonMisionActiva: "INK_SAC custom-model-data:1461"
  botonMisionCompletada: "INK_SAC custom-model-data:1458"
  botonMisionBloqueada: "INK_SAC custom-model-data:1460 name:&c¡Misión_no_disponible! lore:&r_;&7Supera_la_misión_anterior."