compass:
  checkpointMuerte:
    name: Punto de control del Fuego Fatuo
    location: "%math.calc:ph.angelchest_x_1*1%;%math.calc:ph.angelchest_y_1*1%;%math.calc:ph.angelchest_z_1*1%;world"
    item: iconoCheckpointMuerte

events:
  establecerCheckpointMuerte: "folder agregarCheckpointMuerte,iniciarObjLlegarCheckpointMuerte,notificacionCheckpointMuerte"
  agregarCheckpointMuerte: "compass add checkpointMuerte"
  iniciarObjLlegarCheckpointMuerte: "objective start objLlegarCheckpointMuerte"
  notificacionCheckpointMuerte: "notify &6Se ha fijado tu lugar de muerte en la brújula."

  eliminacionCheckpointMuerte: "folder eliminarCheckpointMuerte,notificacionEliminarCheckpointMuerte"
  eliminarCheckpointMuerte: "compass del checkpointMuerte"
  notificacionEliminarCheckpointMuerte: "notify &aHas llegado a tu lugar de muerte anterior."

objectives:
  objLlegarCheckpointMuerte: "location %ph.angelchest_x_1%;%ph.angelchest_y_1%;%ph.angelchest_z_1%;%ph.angelchest_world_1% 5 events:eliminacionCheckpointMuerte"

items:
  iconoCheckpointMuerte: "SOUL_CAMPFIRE"