events:
  establecerCheckpointMuerte: "folder agregarCheckpointMuerte,iniciarObjLlegarCheckpointMuerte,notificacionCheckpointMuerte"
  agregarCheckpointMuerte: "compasstrack %ph.angelchest_x_1%;%ph.angelchest_y_1%;%ph.angelchest_z_1%;%ph.angelchest_world_1%"
  iniciarObjLlegarCheckpointMuerte: "objective start objLlegarCheckpointMuerte"
  notificacionCheckpointMuerte: "notify &6Se ha fijado tu lugar de muerte en la brújula."

  eliminacionCheckpointMuerte: "folder eliminarCheckpointMuerte,notificacionEliminarCheckpointMuerte"
  eliminarCheckpointMuerte: "clearcompass"
  notificacionEliminarCheckpointMuerte: "notify &aHas llegado a tu lugar de muerte anterior."

objectives:
  objLlegarCheckpointMuerte: "location %ph.angelchest_x_1%;%ph.angelchest_y_1%;%ph.angelchest_z_1%;%ph.angelchest_world_1% 5 events:eliminacionCheckpointMuerte"