conditions:
  misionActiva68: "tag marcaMisionActiva68"
  misionCompletada68: "tag marcaMisionCompletada68"

####################################################################################################

events:
  iniciarMision68: "folder agregarMarcaMisionActiva68,iniciarObjetivoMision68"
  agregarMarcaMisionActiva68: "tag add marcaMisionActiva68"
  iniciarObjetivoMision68: "objective start objMatarGolemZafiro"
  
  mensajeAyudaMision68: "notify \n&6&lMisión 68:\n&r Los &bGolems de Zafiro &rson unas criaturas monolíticas que parecen estar hechas de &bPiedra&r y &bZafiro&r, se invocan con un huevo que puedes fabricar, puedes ver la receta de este en una &bMesa de trabajo&r\n&r"

  completarMision68: "folder eliminarMarcaMisionActiva68,agregarMarcaMisionCompletada68,notificacionMisionCompletada68,recompensaMision68,recompensaExpPrestigio,notificacionRecompensaExpPrestigio delay:1"
  eliminarMarcaMisionActiva68: "tag delete marcaMisionActiva68"
  agregarMarcaMisionCompletada68: "tag add marcaMisionCompletada68"
  notificacionMisionCompletada68: ""run ^notify &7----------------------------------------\n&6&l¡Misión 68 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7---------------------------------------- ^notify io:sound soundcategory:players sound:ui.toast.challenge_complete"
  recompensaMision68: "command eco give %player% 1500"
  recompensaExpPrestigio: "mmoprofessionexperience prestigio 1000"
  notificacionRecompensaExpPrestigio: "notify &aHas conseguido 750 exp de prestigio."

####################################################################################################

objectives:
  objMatarGolemZafiro: "mmobkill diamondgolem amount:1 events:completarMision68"