conditions:
  misionActiva20: "tag marcaMisionActiva20"
  misionCompletada20: "tag marcaMisionCompletada20"
  llegarNivel5Clase: "mmoclass * 5"

####################################################################################################

events:
  iniciarMision20: "folder agregarMarcaMisionActiva20,iniciarObjetivoMision20"
  agregarMarcaMisionActiva20: "tag add marcaMisionActiva20"
  iniciarObjetivoMision20: "objective start objSubirNivel5Clase"
  
  mensajeAyudaMision20: "notify \n&6&lMisión 20:\n&r Conforme vayas derrotando enemigos o subiendo de nivel tus profesiones irás obteniendo experiencia para subir de nivel. Los jefes de mazmorras otorgan una mayor cantidad de experiencia al ser derrotados.\n&r"
  
  completarMision20: "folder eliminarMarcaMisionActiva20,agregarMarcaMisionCompletada20,notificacionMisionCompletada20,recompensaMision20,recompensaComida,recompensaReparador,recompensaReparadorMensaje,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva20: "tag delete marcaMisionActiva20"
  agregarMarcaMisionCompletada20: "tag add marcaMisionCompletada20"
  notificacionMisionCompletada20: ""run ^notify &7----------------------------------------\n&6&l¡Misión 20 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7---------------------------------------- ^notify io:sound soundcategory:players sound:ui.toast.challenge_complete"
  recompensaMision20: "command eco give %player% 200"
  recompensaComida: "run ^command give %player% bread 6 ^notify &aHas conseguido 6 Panes."
  recompensaReparador: "mmoitemgive CONSUMABLE REPARADOR_250 2"
  recompensaReparadorMensaje: "notify &aHas conseguido 2 Reparadores Básicos."
  recompensaExpClase: "mmoclassexperience 200"
  notificacionRecompensaExpClase: "notify &aHas conseguido 200 exp de clase."

####################################################################################################

objectives:
  objSubirNivel5Clase: "delay 5 ticks interval:5 conditions:llegarNivel5Clase events:completarMision20"