conditions:
  misionActiva33: "tag marcaMisionActiva33"
  misionCompletada33: "tag marcaMisionCompletada33"
  tenerReparadorDorado: "mmoitem CONSUMABLE REPARADOR_500"

####################################################################################################

events:
  mensajeAyudaMision33: "notify \n&6&lMisión 33:&r Debes fabricar un &bReparador Dorado&r, para ello necesitarás &b4 bloques de oro&r, &bun Yunque &ry &b2 de Mythril&r.\n&r"
  
  iniciarMision33: "folder agregarMarcaMisionActiva33,iniciarObjetivoMision33"
  agregarMarcaMisionActiva33: "tag add marcaMisionActiva33"
  iniciarObjetivoMision33: "objective start objFabricarReparadorDorado"
  
  completarMision33: "folder eliminarMarcaMisionActiva33,agregarMarcaMisionCompletada33,notificacionMisionCompletada33,recompensaMision33,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva33: "tag delete marcaMisionActiva33"
  recompensaMision33: "command eco give %player% 300"
  recompensaExpClase: "mmoclassexperience 150"
  notificacionRecompensaExpClase: "notify &aHas conseguido 150 exp de clase."
  agregarMarcaMisionCompletada33: "tag add marcaMisionCompletada33"
  notificacionMisionCompletada33: "notify &7----------------------------------------\n&6&l¡Misión 33 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7----------------------------------------"

####################################################################################################

objectives:
  objFabricarReparadorDorado: "delay 5 ticks interval:5 conditions:tenerReparadorDorado events:completarMision33"