conditions:
  misionActiva79: "tag marcaMisionActiva79"
  misionInfoRecibidaNigromante: "tag marcaInfoRecibidaNigromante"
  misionInfoRecibidaNigromante_2: "tag marcaInfoRecibidaNigromante_2"
  misionAceptadaNigromante: "tag marcaMisionAceptadaNigromante"
  mazmorraCompletadaNigromante: "tag marcaMazmorraCompletadaNigromante"
  misionCompletada79: "tag marcaMisionCompletada79"

#####################################################################        

objectives:
  completarMazmorraNigromante: "finishdungeon nigromante events:mazmorraCompletarNigromante"

#####################################################################        

events:
  iniciarMision79: "tag add marcaMisionActiva79"
  
  mensajeAyudaMision79: "folder mensajeAyudaMision79_1,mensajeAyudaMision79_2,mensajeAyudaMision79_3,mensajeAyudaMision79_4,mensajeAyudaMision79_5,mensajeAyudaMision79_6"
  mensajeAyudaMision79_1: "notify \n&6&lMisión 79:\n&r El &6Rey de Valor &rse encuentra en el Salón del Trono del Palacio de Valor, el cual está ubicado en el &a/spawn&r.\n&r conditions:!misionInfoRecibidaNigromante"
  mensajeAyudaMision79_2: "notify \n&6&lMisión 79:\n&r Debes hablar con el &bMago de la Corte Real &rque se encuentra en la Biblioteca del Palacio de Valor, el cual está ubicado en el &a/spawn&r.\n&r conditions:misionInfoRecibidaNigromante,!misionInfoRecibidaNigromante_2,!misionAceptadaNigromante"
  mensajeAyudaMision79_3: "folder agregarObjetivosBrujula conditions:misionInfoRecibidaNigromante,misionInfoRecibidaNigromante_2,!misionAceptadaNigromante,!Misiones_Principiante-Mision_79-Parte_3.cantidadGuardianesDerrotados"
  mensajeAyudaMision79_4: "folder agregarObjetivosBrujula_2 conditions:misionInfoRecibidaNigromante,misionInfoRecibidaNigromante_2,!misionAceptadaNigromante,Misiones_Principiante-Mision_79-Parte_3.cantidadGuardianesDerrotados"
  mensajeAyudaMision79_5: "notify \n&6&lMisión 79:\n&r El cristal de la mazmorra del &aNigromante &rse encuentra saliendo de la ciudad de Valor y siguiendo el camino hasta el rio grande, al pasar por la cripta de este veras el cristal de la mazmorra&r.\n&r conditions:misionAceptadaNigromante,!mazmorraCompletadaNigromante"
  mensajeAyudaMision79_6: "notify \n&6&lMisión 79:\n&r El &6Rey de Valor &rte está esperando en su palacio, el cual está ubicado en el &a/spawn&r.\n&r conditions:misionAceptadaNigromante,mazmorraCompletadaNigromante"
  
  agregarObjetivosBrujula: "folder limpiarBrujula,mostrarBrujula,mostrarObjBrujula1,mostrarObjBrujula2,mostrarObjBrujula3,mostrarObjBrujula4,notificacionObjBrujula"
  limpiarBrujula: "clearcompass"
  mostrarBrujula: "command calebcompass show %player%"
  mostrarObjBrujula1: "command calebcompass toggle %player% altar1 enable condition:!Misiones_Principiante-Mision_79-Parte_3.guardianDerrotado1"
  mostrarObjBrujula2: "command calebcompass toggle %player% altar2 enable condition:!Misiones_Principiante-Mision_79-Parte_3.guardianDerrotado2"
  mostrarObjBrujula3: "command calebcompass toggle %player% altar3 enable condition:!Misiones_Principiante-Mision_79-Parte_3.guardianDerrotado3"
  mostrarObjBrujula4: "command calebcompass toggle %player% altar4 enable condition:!Misiones_Principiante-Mision_79-Parte_3.guardianDerrotado4"
  mostrarObjBrujulaAltar: "compasstrack 1019.5;16;933.5;Zona1"
  notificacionObjBrujula: "notify \n&6&lMisión 79:\n&r Para llegar a tu objetivo ve al &b/spawn &ry sigue la dirección que te indica la brújula (&f ▽ &r).\n&r"
  notificacionObjBrujula_2: "notify \n&6&lMisión 79:\n&r Debes ir al altar elemental teniendo los cuatro &bsellos elementales &ren tu inventario para romper el hechizo. En caso que no tengas los sellos, revisa tu &b/mochilamisiones&r. Para llegar a tu objetivo ve al &b/spawn &ry sigue la dirección que te indica la brújula (&f ▽ &r).\n&r"
  agregarObjetivosBrujula_2: "folder limpiarBrujula,mostrarBrujula,mostrarObjBrujulaAltar,notificacionObjBrujula_2"

  mostrarMensajeAyudaMision79_2: "folder mensajeAyudaMision79_2 delay:2"

  agregarMarcaInfoRecibidaNigromante: "tag add marcaInfoRecibidaNigromante"
  agregarMarcaInfoRecibidaNigromante_2: "tag add marcaInfoRecibidaNigromante_2"

  completarParte1: "folder agregarMarcaInfoRecibidaNigromante,notificacionNuevoMensajeAyuda delay:2 condition:!misionInfoRecibidaNigromante"
  completarParte2: "folder agregarMarcaInfoRecibidaNigromante_2,notificacionNuevoMensajeAyuda,Misiones_Principiante-Mision_79-Parte_3.iniciarParte3 delay:2 conditions:!Misiones_Principiante-Mision_79.misionInfoRecibidaNigromante_2"
  completarParte3: "folder aceptarMisionNigromante delay:1"
  
  aceptarMisionNigromante: "folder agregarMarcaMisionAceptadaNigromante,permisoMazmorraNigromante,iniciarObjetivoCompletarMazmorraNigromante,notificacionNuevoMensajeAyuda delay:1"
  agregarMarcaMisionAceptadaNigromante: "tag add marcaMisionAceptadaNigromante"
  permisoMazmorraNigromante: "command lp user %player% permission set mazmorra.nigromante"
  iniciarObjetivoCompletarMazmorraNigromante: "objective start completarMazmorraNigromante"
  notificacionNuevoMensajeAyuda: "notify &7----------------------------------------\n&6&lMisiones:\n&e¡Tienes un nuevo mensaje de ayuda disponible en el menú de &r/misiones!\n&7----------------------------------------"
  
  eventoayuda: "folder notificacionNuevoMensajeAyuda delay:1"
  
  mazmorraCompletarNigromante: "folder agregarMarcaMazmorraCompletadaNigromante,notificacionNuevoMensajeAyuda delay:1"
  agregarMarcaMazmorraCompletadaNigromante: "tag add marcaMazmorraCompletadaNigromante"
  
  completarMision79: "folder eliminarMarcasMisionActiva79,agregarMarcaMisionCompletada79,notificacionMisionCompletada79,darRecompensaMision,darRecompensaBasilisco,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcasMisionActiva79: "folder eliminarMarcaMisionActiva79,eliminarMarcaMisionInfoRecibidaNigromante,eliminarMarcaMisionInfoRecibidaNigromante_2,eliminarMarcaMisionAceptadaNigromante,eliminarMarcaMazmorraCompletadaNigromante,eliminarMarcaConjuroDesactivado,eliminarMarcasGuardianesDerrotados"
  eliminarMarcaMisionActiva79: "tag delete marcaMisionActiva79"
  eliminarMarcaMisionInfoRecibidaNigromante: "tag delete marcaInfoRecibidaNigromante"
  eliminarMarcaMisionInfoRecibidaNigromante_2: "tag delete marcaInfoRecibidaNigromante_2"
  eliminarMarcaMisionAceptadaNigromante: "tag delete marcaMisionAceptadaNigromante"
  eliminarMarcaConjuroDesactivado: "tag delete Misiones_Principiante-Mision_79-Parte_3.marcaConjuroDesactivado"
  eliminarMarcasGuardianesDerrotados: "run ^tag delete Misiones_Principiante-Mision_79-Parte_3.marcaGuardianDerrotado1 ^tag delete Misiones_Principiante-Mision_79-Parte_3.marcaGuardianDerrotado2 ^tag delete Misiones_Principiante-Mision_79-Parte_3.marcaGuardianDerrotado3 ^tag delete Misiones_Principiante-Mision_79-Parte_3.marcaGuardianDerrotado4 ^deletepoint Misiones_Principiante-Mision_79-Parte_3.guardianesDerrotados"
  eliminarMarcaMazmorraCompletadaNigromante: "tag delete marcaMazmorraCompletadaNigromante"
  agregarMarcaMisionCompletada79: "tag add marcaMisionCompletada79"
  notificacionMisionCompletada79: "run ^notify &7----------------------------------------\n&6&l¡Misión 79 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7---------------------------------------- ^notify io:sound soundcategory:players sound:ui.toast.challenge_complete"
  darRecompensaMision: "command eco give %player% 15000"
<<<<<<< HEAD
  darRecompensaBasilisco: "run ^command lp user %player% permission set mcpets.basilisk_obsidian ^notify &aHas conseguido una nueva montura: &6Basilisco de Obsidiana&a.&e Usa &f/mascotas &epara ver tu nueva montura."
=======
  darRecompensaBasilisco: "run ^command lp user %player permission set mcpets.basilisk_obsidian ^notify &aHas conseguido una nueva montura: &6Basilisco de Obsidiana&a.&e Usa &f/mascotas &epara ver tu nueva montura."
>>>>>>> 1090e9aa2912d20e175079ad4636cf412d928e76
  recompensaExpClase: "mmoclassexperience 1500"
  notificacionRecompensaExpClase: "notify &aHas conseguido 1500 exp de clase."