package:
  templates:
    - Sistema_Puertas-Puertas

variables:
  ubicacionEntrada: 1041.5;19;933.5;Zona1
  pitchYawEntrada: -90;0
  ubicacionSalida: 1034.5;19;933.5;Zona1
  pitchYawSalida: 90;0
  mensajeEntrada: "&6Has entrado en la Cripta del Nigromante"
  mensajeSalida: "&6Has salido de la Cripta del Nigromante"