conditions:
  misionActiva3: "tag marcaMisionActiva3"
  misionCompletada3: "tag marcaMisionCompletada3" 
  bloqueProteccionNoColocado: "variable %math.calc:ph.protectionstones_currentplayer_num_of_owned_regions*1% 0"

####################################################################################################

events:
  iniciarMision3: "folder agregarMarcaMisionActiva3,iniciarObjetivoMision3"
  agregarMarcaMisionActiva3: "tag add marcaMisionActiva3"
  iniciarObjetivoMision3: "objective start objColocarBloqueProteccion"
  
  mensajeAyudaMision3: "notify \n&6&lMisión 3:\n&r La Tienda de Protecciones está ubicada en las cercanías del &b/spawn&r, allí puedes comprar un nuevo Bloque de Protección por &a50 Rupias &rsi perdiste el que tenías.\n&r \n &c&oNota: Es importante que busques rápido un lugar donde colocar la protección ya que dentro de esta no aparecen enemigos.\n&r "
  
  completarMision3: "folder eliminarMarcaMisionActiva3,agregarMarcaMisionCompletada3,notificacionMisionCompletada3,recompensaMision3,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva3: "tag delete marcaMisionActiva3"
  agregarMarcaMisionCompletada3: "tag add marcaMisionCompletada3"
  notificacionMisionCompletada3: ""run ^notify &7----------------------------------------\n&6&l¡Misión 3 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7---------------------------------------- ^notify io:sound soundcategory:players sound:ui.toast.challenge_complete"
  recompensaMision3: "command eco give %player% 100"
  recompensaExpClase: "mmoclassexperience 50"
  notificacionRecompensaExpClase: "notify &aHas conseguido 50 exp de clase."

####################################################################################################

objectives:
  objColocarBloqueProteccion: "delay 5 ticks interval:5 conditions:!bloqueProteccionNoColocado events:completarMision3"