conditions:
  requerimientoEntradaPuerta: "location $ubicacionSalida$ 5"
  requerimientoSalidaPuerta: "location $ubicacionEntrada$ 5"
  # pasandoPuerta: "tag marcaPasandoPuerta"

events:
  eventoPuerta: "if requerimientoEntradaPuerta eventoEntradaPuerta else eventoPuerta2"
  eventoPuerta2: "if requerimientoSalidaPuerta eventoSalidaPuerta else eventoErrorPuerta"
  eventoErrorPuerta: "notify &cNo estás en el lugar correcto para usar este tirador."
  eventoEntradaPuerta: "folder eventoEntrada,notificacionEntrada,notificacionSonidoEntrada"
  eventoEntrada: "teleport $ubicacionEntrada$;$pitchYawEntrada$"
  notificacionEntrada: "notify io:title $mensajeEntrada$"
  notificacionSonidoEntrada: "notify io:sound soundcategory:blocks sound:$efectoSonidoEntrada$"
  eventoSalidaPuerta: "folder eventoSalida,notificacionSalida,notificacionSonidoSalida"
  eventoSalida: "teleport $ubicacionSalida$;$pitchYawSalida$"
  notificacionSalida: "notify io:title $mensajeSalida$"
  notificacionSonidoSalida: "notify io:sound soundcategory:blocks sound:$efectoSonidoSalida$"

  # agregarMarcaPasandoPuerta: "tag add marcaPasandoPuerta"
  # eliminarMarcaPasandoPuerta: "tag delete marcaPasandoPuerta"

# objectives:
#   objEliminarMarcaPasandoPuerta: "delay 1 events:eliminarMarcaPasandoPuerta"

variables:
  ubicacionEntrada: 0;0;0;Zona1
  pitchYawEntrada: 0;0
  ubicacionSalida: 0;0;0;Zona1
  pitchYawSalida: 0;0
  mensajeEntrada: "&6Has entrado al Lugar"
  mensajeSalida: "&6Has salido del Lugar"
  efectoSonidoEntrada: block.iron_door.open
  efectoSonidoSalida: block.iron_door.close