conditions:
  requerimientoEntradaPuerta: "location $ubicacionSalida$ 5"
  requerimientoSalidaPuerta: "location $ubicacionEntrada$ 5"
  entrandoPuerta: "tag marcaEntrandoPuerta"
  saliendoPuerta: "tag marcaSaliendoPuerta"

events:
  eventoPuerta: "folder eventoEntrarPuerta,eventoSalirPuerta"
  eventoEntrarPuerta: "folder agregarMarcaEntrandoPuerta,iniciarObjEntrarPuerta,eventoEntrada,notificacionEntrada,notificacionSonidoEntrada condition:requerimientoEntradaPuerta"
  agregarMarcaEntrandoPuerta: "tag add marcaEntrandoPuerta condition:!entrandoPuerta"
  iniciarObjEntrarPuerta: "objective start objEntrarPuerta condition:entrandoPuerta"
  eventoEntrada: "teleport $ubicacionEntrada$;$pitchYawEntrada$ condition:!saliendoPuerta"
  notificacionEntrada: "notify io:title $mensajeEntrada$ condition:!saliendoPuerta"
  notificacionSonidoEntrada: "notify io:sound soundcategory:blocks sound:$efectoSonidoEntrada$ condition:!saliendoPuerta"
  eventoSalirPuerta: "folder agregarMarcaSaliendoPuerta,iniciarObjSalirPuerta,eventoSalida,notificacionSalida,notificacionSonidoSalida condition:requerimientoSalidaPuerta"
  agregarMarcaSaliendoPuerta: "tag add marcaSaliendoPuerta condition:!saliendoPuerta"
  iniciarObjSalirPuerta: "objective start objSalirPuerta condition:saliendoPuerta"
  eventoSalida: "teleport $ubicacionSalida$;$pitchYawSalida$ condition:!entrandoPuerta"
  notificacionSalida: "notify io:title $mensajeSalida$ condition:!entrandoPuerta"
  notificacionSonidoSalida: "notify io:sound soundcategory:blocks sound:$efectoSonidoSalida$ condition:!entrandoPuerta"
  
  eliminarMarcaEntrandoPuerta: "tag delete marcaEntrandoPuerta"
  eliminarMarcaSaliendoPuerta: "tag delete marcaSaliendoPuerta"

objectives:
  objEntrarPuerta: "delay 2 events:eliminarMarcaEntrandoPuerta"
  objSalirPuerta: "delay 2 events:eliminarMarcaSaliendoPuerta"

variables:
  ubicacionEntrada: 0;0;0;Zona1
  pitchYawEntrada: 0;0
  ubicacionSalida: 0;0;0;Zona1
  pitchYawSalida: 0;0
  mensajeEntrada: "&6Has entrado al Lugar"
  mensajeSalida: "&6Has salido del Lugar"
  efectoSonidoEntrada: block.iron_door.open
  efectoSonidoSalida: block.iron_door.close