package:
  templates:
    - Checkpoint_Muerte-Checkpoints

compass:
  checkpointMuerte:
    name: Punto de control del Fuego Fatuo &7[&eS1&7]
    location: "%math.calc:ph.angelchest_x_1*1%;%math.calc:ph.angelchest_y_1*1%;%math.calc:ph.angelchest_z_1*1%;world"
    item: iconoCheckpointMuerte