package:
  templates:
    - Sistema_Puertas-Puertas

variables:
  ubicacionEntrada: -89.5;89;768.5;Zona1
  pitchYawEntrada: 90;0
  ubicacionSalida: 36.5;98;766.5;Zona1
  pitchYawSalida: -90;0
  mensajeEntrada: "&6Has entrado en la Fortaleza de Anabor"
  mensajeSalida: "&6Has salido de la Fortaleza de Anabor"