conditions:
  misionActiva6: "tag marcaMisionActiva6"
  misionCompletada6: "tag marcaMisionCompletada6"

####################################################################################################

events:
  iniciarMision6: "folder agregarMarcaMisionActiva6,iniciarObjetivoMision6"
  agregarMarcaMisionActiva6: "tag add marcaMisionActiva6"
  iniciarObjetivoMision6: "objective start objMinarPiedra"
  
  mensajeAyudaMision6: "notify \n&6&lMisión 6:\n&r Debes minar &b20 bloques de Piedra&r, para ello necesitarás fabricar un &bPico &rde cualquier madera o mineral que tengas disponible.\n\n&c&o Nota: Colocar bloques de tu inventario aumentará la cantidad de bloques que debes minar para cumplir la misión, ya que se considera como hacer trampa.\n&r"
  
  completarMision6: "folder eliminarMarcaMisionActiva6,agregarMarcaMisionCompletada6,notificacionMisionCompletada6,recompensaMision6,recompensaExpClase,notificacionRecompensaExpClase delay:1"
  eliminarMarcaMisionActiva6: "tag delete marcaMisionActiva6"
  agregarMarcaMisionCompletada6: "tag add marcaMisionCompletada6"
  notificacionMisionCompletada6: "notify &7----------------------------------------\n&6&l¡Misión 6 completada!\n \n&7Usa &r/misiones &7para activar tu siguiente misión.\n&7----------------------------------------"
  recompensaMision6: "command eco give %player% 100"
  recompensaExpClase: "mmoprofessionexperience mining 100"
  notificacionRecompensaExpClase: "notify &aHas conseguido 100 exp de mineria."

####################################################################################################

objectives:
  objMinarPiedra: "block STONE -20 events:completarMision6 notify:5"