conditions:
  estarEnMundoExploracion: "world world"
  estarEnNether: "world Zona1_nether"
  estarEnUnMundoValido: "or estarEnMundoExploracion,estarEnNether"
  permisoMantenerInventario: "permission essentials.keepinv"

  checkpointMuerteActivo: "tag marcaCheckpointMuerteActivo"

objectives:
  objCheckpointMuerte: "die events:establecerCheckpointMuerte conditions:estarEnUnMundoValido,!permisoMantenerInventario persistent"
  # objComprobarServidorCheckpointMuerte: "login events:comprobarCheckpointMuerteAMostrar persistent"

events:
  activacionCheckpointMuerte: "folder activarCheckpointMuerte,agregarMarcaCheckpointMuerteActivo,notificacionCheckpointMuerteActivado"
  activarCheckpointMuerte: "objective start objCheckpointMuerte"
  agregarMarcaCheckpointMuerteActivo: "tag add marcaCheckpointMuerteActivo"
  notificacionCheckpointMuerteActivado: "notify &aHas activado el punto de control del fuego fatuo."
  
  desactivacionCheckpointMuerte: "folder desactivarCheckpointMuerte,eliminarMarcaCheckpointMuerteActivo,notificacionCheckpointMuerteDesactivado"
  desactivarCheckpointMuerte: "objective delete objCheckpointMuerte"
  eliminarMarcaCheckpointMuerteActivo: "tag delete marcaCheckpointMuerteActivo"
  notificacionCheckpointMuerteDesactivado: "notify &cHas desactivado el punto de control del fuego fatuo."
  
  establecerCheckpointMuerte: "folder establecerCheckpointMuerteServidor"