conditions:
  estarEnSpawn: "world Zona1"
  estarEnMundoExploracion: "world world"
  estarEnNether: "world Zona1_nether"
  estarEnEnd: "world Zona1_end"
  estarEnUnMundoValido: "or estarEnSpawn,estarEnMundoExploracion,estarEnNether,estarEnEnd"

  checkpointMuerteActivado: "tag marcaCheckpointMuerteActivado"

  checkpointMuerteActivo: "variable %ph.servervariables_value_checkpoint_muerte_activo% true"

objectives:
  objCheckpointMuerte: "die events:Checkpoint_Muerte-Checkpoints.establecerCheckpointMuerte conditions:estarEnUnMundoValido persistent"
  objComprobarEstadoCheckpointMuerte: "login events:comprobarCheckpointMuerteAMostrar persistent"

events:
  activacionCheckpointMuerte: "folder activarCheckpointMuerte,notificacionCheckpointMuerteActivado"
  activarCheckpointMuerte: "run ^objective start objCheckpointMuerte ^objective start objComprobarEstadoCheckpointMuerte ^tag add marcaCheckpointMuerteActivado"
  notificacionCheckpointMuerteActivado: "notify &aHas activado el punto de control de muerte."
  
  desactivacionCheckpointMuerte: "folder Checkpoint_Muerte-Checkpoints.desactivarCheckpointMuerteActivo,desactivarCheckpointMuerte,notificacionCheckpointMuerteDesactivado"
  desactivarCheckpointMuerte: "run ^objective delete objCheckpointMuerte ^objective delete objComprobarEstadoCheckpointMuerte ^tag delete marcaCheckpointMuerteActivado"
  notificacionCheckpointMuerteDesactivado: "notify &cHas desactivado el punto de control de muerte."

  comprobarCheckpointMuerteAMostrar: "folder Checkpoint_Muerte-Checkpoints.agregarCheckpointMuerte,notificacionCheckpointMuerteActivo condition:checkpointMuerteActivo"
  notificacionCheckpointMuerteActivo: "notify &6Tienes un punto de control de muerte activo en el %ph.servervariables_display_checkpoint_muerte_mundo% de este servidor. delay:1"