menus:
  menuMisiones:
    height: 6
    title: "§f§f㊑"
    slots:
      47: "botonPaginaAnterior"
      # 49: "botonVolverMenuPrincipal"
      10: "botonMisionDisponible57,botonMisionActiva57,botonMisionCompletada57,botonMisionBloqueada57"
      11: "botonMisionDisponible58,botonMisionActiva58,botonMisionCompletada58,botonMisionBloqueada58"
    items:
      botonPaginaAnterior:
        item: "paginaAnterior"
        close: true
        text:
        - "&7[&aClic&7] para ir a la página anterior."
        click: "abrirPaginaAnterior" 
      # botonVolverMenuPrincipal:
      #   item: "paginaAnterior"
      #   amount: 1
      #   close: true
      #   text:
      #   - "&7[&aClic&7] para ir al menú principal."
      #   click: "abrirMenuPrincipal"
#####################################################################
      botonMisionDisponible57:
        item: "botonMisionActiva"
        conditions: "Misiones_Principiante-Mision_56.misionCompletada56,!Misiones_Principiante-Mision_57.misionActiva57,!Misiones_Principiante-Mision_57.misionCompletada57"
        close: true
        text:
        - "&6&l[Misión 57]: &eUn caldero de crianza"
        - "&r "
        - "&aObjetivo:"
        - "&7&oFabrica y usa un &f&oCaldero de mascotas."
        - "&r "
        - "&7[&aClic izquierdo&7] para iniciar la misión."
        click:
          left: "Misiones_Principiante-Mision_57.mensajeAyudaMision57,Misiones_Principiante-Mision_57.iniciarMision57" 
      botonMisionActiva57:
        item: "botonMisionActiva"
        conditions: "Misiones_Principiante-Mision_57.misionActiva57"
        close: true
        text:
        - "&6&l[Misión 57]: &eUn caldero de crianza"
        - "&r "
        - "&aObjetivo:"
        - "&7&oFabrica y usa un &f&oCaldero de mascotas."
        - "&r "
        - "&7[&aClic izquierdo&7] para recibir un mensaje de ayuda acerca de la misión."
        click:
          left: "Misiones_Principiante-Mision_57.mensajeAyudaMision57" 
      botonMisionCompletada57:
        item: "botonMisionCompletada"
        conditions: "Misiones_Principiante-Mision_57.misionCompletada57"
        text:
        - "&2¡Misión completada!"
        - "&6&l[Misión 57]: &eUn caldero de crianza"
        - "&r "
        - "&7&oFabrica y usa un &f&oCaldero de mascotas."
      botonMisionBloqueada57:
        item: "botonMisionBloqueada"
        conditions: "!Misiones_Principiante-Mision_56.misionCompletada56"
#####################################################################
      botonMisionDisponible58:
        item: "botonMisionActiva"
        conditions: "Misiones_Principiante-Mision_57.misionCompletada57,!Misiones_Principiante-Mision_58.misionActiva58,!Misiones_Principiante-Mision_58.misionCompletada58"
        close: true
        text:
        - "&6&l[Misión 58]: &eComida de mascotas"
        - "&r "
        - "&aObjetivo:"
        - "&7&oFabrica &f&oPienso básico de mascotas."
        - "&r "
        - "&7[&aClic izquierdo&7] para iniciar la misión."
        click:
          left: "Misiones_Principiante-Mision_58.mensajeAyudaMision58,Misiones_Principiante-Mision_58.iniciarMision58" 
      botonMisionActiva58:
        item: "botonMisionActiva"
        conditions: "Misiones_Principiante-Mision_58.misionActiva58"
        close: true
        text:
        - "&6&l[Misión 58]: &eComida de mascotas"
        - "&r "
        - "&aObjetivo:"
        - "&7&oFabrica &f&oPienso básico de mascotas."
        - "&r "
        - "&7[&aClic izquierdo&7] para recibir un mensaje de ayuda acerca de la misión."
        click:
          left: "Misiones_Principiante-Mision_58.mensajeAyudaMision58" 
      botonMisionCompletada58:
        item: "botonMisionCompletada"
        conditions: "Misiones_Principiante-Mision_58.misionCompletada58"
        text:
        - "&2¡Misión completada!"
        - "&6&l[Misión 58]: &eComida de mascotas"
        - "&r "
        - "&7&oFabrica &f&oPienso básico de mascotas."
      botonMisionBloqueada58:
        item: "botonMisionBloqueada"
        conditions: "!Misiones_Principiante-Mision_57.misionCompletada57"
#####################################################################

events:
  abrirPaginaAnterior: "menu open Misiones_Principiante-Menu-Menu_2.menuMisiones"
  # abrirMenuPrincipal: "menu open Menu_Principal_Misiones.menuMisiones"

#####################################################################

items:
  botonMisionActiva: "INK_SAC custom-model-data:1461"
  botonMisionCompletada: "INK_SAC custom-model-data:1458"
  botonMisionBloqueada: "INK_SAC custom-model-data:1460 name:&c¡Misión_no_disponible! lore:&r_;&7Supera_la_misión_anterior."
  paginaAnterior: "PAPER custom-model-data:1802"
  # volverMenuPrincipal: "PAPER custom-model-data:1807"